name: CD | GitHub Pages Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
        working-directory: ./server   # Specify the directory where package.json for server exists

      - name: Start Server
        run: npm start &   # Start the server in the background
        working-directory: ./server   # Specify the directory where package.json for server exists

      # Add additional steps (e.g., running tests, deploying to GitHub Pages)

      - name: Check for Changes
        run: git diff --quiet || (git add . && git commit -m "Deploy to GitHub Pages")

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.email "it21108990@my.sliit.lk"
          git config --global user.name "kaveenexe"
          git push -f https://${{ secrets.GH_PAT }}@github.com/kaveenexe/CTSE_Assignment_02.git main
