name: CICD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install trivy      # Install trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
      - name: Install dependencies
        run: npm install
        working-directory: ./server
      - name: Dependency Vulnerability Scan     # Dependency vulnerability scan
        run: npm audit --production
        working-directory: ./server
      - name: Run tests      # Unit test
        run: npm test
        working-directory: ./server
      - name: Login to Docker Hub       # Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
      - name: Build Docker image
        run: docker build -t kaveendev/ctse-assignment .
      - name: Docker Image Security Scan      # Docker image vulnerability security scan
        run: trivy image kaveendev/ctse-assignment:latest
      - name: Publish image to Docker Hub
        run: docker push kaveendev/ctse-assignment:latest
  
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull kaveendev/ctse-assignment:latest
      - name: Delete old container
        run: docker rm -f ctse-assignment-container
      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name ctse-assignment-container kaveendev/ctse-assignment